version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: user-auth-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_auth_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: user-auth-api
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://postgres:password@postgres:5432/user_auth_db?schema=public'
      JWT_SECRET: 'your-jwt-secret-key'
    depends_on:
      - postgres
    command: sh -c "npx prisma migrate deploy && yarn start:dev"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data:
